server:
  port: 9090
neinei: lwq

msg1: 'hhehe \n haha' # 单引忽略转义字符

msg2: "hhehe \n haha" # 双引识别转义字符

iphone: 18Pro

appid: 99999

person:
  hehe: hehe #测试配置文件和代码写死的优先级,配置文件的优先级更高呀
  name: lwq
  age: 23
  birth: 1999/12/12 20:20:20
  title:
    - 龙族盟友
    - 传说
  pet:
    species: dog
    name: ahuang
  list:
    - 14pro
    - ${iphone}
  map1:
    english: good
    math: good
  map2:
    dog:
      - { species: dog, name: ahuang }
      - { species: dog, name: alv }
    cat:
      - { species: cat, name: mimi }
      - { species: cat, name: miaomiao }
  map3:
    dog:
      - species: dog
        name: ahuang
      - species: dog
        name: alv
    cat:
      - species: cat
        name: mimi
      - species: cat
        name: miaomiao
  list-pet:
    # - {species: cat,name: mimi}
    # - {species: cat,name: miaomiao}

    # - species: cat
    #   name: mimi
    # - species: cat
    #   name: miaomiao

    [{ species: cat, name: mimi }, { species: cat, name: miaomiao }]

logging:
  file:
    name: logs/lwq.log
  level:
    root: info
