msg1: 'hhehe \n haha'       # 单引忽略转义字符

msg2: "hhehe \n haha"       # 双引识别转义字符

person:
  name: lwq
  age: 23
  birth: 1999/12/12 20:20:20
  title: 
    - 龙族盟友
    - 传说
  pet:
    species: dog
    name: ahuang
  list:
    - 14pro
    - 15pro
  map1:
    english: good
    math: good
  map2:
    dog:
      - {species: dog,name: ahuang}
      - {species: dog,name: alv}
    cat:
      - {species: cat,name: mimi}
      - {species: cat,name: miaomiao}
  map3:
    dog:
      - species: dog
        name: ahuang
      - species: dog
        name: alv
    cat:
      - species: cat
        name: mimi
      - species: cat
        name: miaomiao

  






