# datasource
spring:
  datasource:
    url: jdbc:mysql:///db1001
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
