
logging:
  file: 
    name: logs/lwq.log
  level:
    root: info

server:
  port: 7789

springdoc:
  swagger-ui:
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/test会自动重定向到swagger页面
    path: /hehe
    #请求时间
    display-request-duration: true

   
   





