spring:
  datasource:
    url: jdbc:mysql:///db1001?serverTimezone=UTC   #serverTimezone在低版本可能会用到
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver   #cj是新版的，旧版的一般都不用了
