spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://43.143.216.21:3306/hehe_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"
    username: root
    password: Aa@111111
  #jpa相关配置(和datasource同级)
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create
                #none 什么也不做
                #create: 每次运行应用程序时，都会重新创建表，所以，数据都会丢失
                #create-drop:每次运行程序时会创建表结构，然后程序结束时清空数据
                #update: 每次运行程序没有表时会创建表，如果对象改变会更新表结构，原有数据不会清除，只会更新
                #validate: 运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
    open-in-view: false   # 默认为true(是指延时加载的一些属性数据，可以在页面展现的时候，保持session不关闭，从而保证能在页面进行延时加载?)
    properties:
      hibernate:
       #show_sql: true    #输出sql语句
       #format_sql: true  #格式化输出的sql，否则会一行显示
       #user_query_cache: true  #这条还没弄会
        jdbc: 
          fetch_size: 100
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
       